### ISSUE TITLE
Ignoring files

### ISSUE THREAD

**Issue by rtsao** [dtinth/babel-plugin-__coverage__#2]
The current filename is available in visitors in the state parameter, for example:

```javascript
Identifier(path, state) {
    console.log(state.file.opts.filename);
}
```

I'd like to use this feature to be able to ignore files that satisfy a glob or multiple globs (probably using `minimatch`). I'd be happy to implement this in a PR if you'd be willing to entertain the idea.

I'm thinking the external API would look like this:

```
{
  "plugins": [["babel-plugin-__coverage__", {
    "ignore": ["**/test/**"]
  }]]
}
```

**Comment by dtinth** [comment]
Hello. I agree about your ideas. I would very welcome the patch. :smiley:

[babel-plugin-transform-anada](https://github.com/adana-coverage/babel-plugin-transform-adana) also does this. They are using a combination of `only` and `ignore` options, closely following [Babel’s configuration format](https://babeljs.io/docs/usage/options/).

**Comment by kentcdodds** [comment]
Given a little bit of direction, I'd love to add this patch.

**Comment by dtinth** [comment]
Here’s how [babel-plugin-transform-adana](https://github.com/adana-coverage/babel-plugin-transform-adana/blob/64807a0d4b048b40dc1990d95d504b0a02022652/src/instrumenter.js#L523) does it. :smile:

**Comment by kentcdodds** [comment]
I've found a workaround that may just work for me for now:

```js
function getJSLoaders() {
  var jsLoaders = [];
  var presets = ['es2015-webpack', 'stage-2']
  if (process.env.NODE_ENV === 'test') {
    jsLoaders.push({
      test: /js\/.*\.js$/,
      loader: 'babel',
      exclude: /node_modules/,
      query: {
        presets: presets,
        plugins: ['__coverage__'],
      },
    });
    jsLoaders.push({
      test: /test\/.*\.js$/,
      loader: 'babel',
      exclude: /node_modules/,
      query: {
        presets: presets,
      },
    });
  } else {
    jsLoaders.push({
      test: /\.js$/,
      loader: 'babel',
      exclude: /node_modules/,
      query: {
        presets: presets,
      }
    });
  }
  return jsLoaders;
}
```

Basically use webpack to determine the babel config for each type of file. This'll work for me for now. Maybe I'll come back and implement this built in because that would be handy, but ¯\_(ツ)_/¯

**Comment by kentcdodds** [comment]
Heh, I decided to work on it anyway. It's much cleaner :-)
