### ISSUE TITLE
1.0 release for semver

### ISSUE THREAD

**Issue by rtsao** [dtinth/babel-plugin-__coverage__#29]
Do you foresee any breaking changes in the near term? A 1.0 release would be nice for semantic versioning purposes and consumers of this library.

Great work on the plugin, BTW 😄

**Comment by dtinth** [comment]
Hello. Thanks!

Right now I don’t foresee any breaking changes, and I understand that going 1.0.0 makes people feel assuring. At least there’s no more “anything can happen in 0._x_,” although I do follow a convention where breaking changes in 0.𝒙 are represented as an increment of 𝒙.

I think if it’s stable enough I’d just release 1.0.0 without any change. Perhaps this week. 😄

**Comment by dtinth** [comment]
Released 1.11.111!!!!!!!1111!!!11 🎉
